### ISSUE TITLE
Possibility to use an organization url?

### ISSUE THREAD

**Issue by NoahNxT** [Lukasss93/laravel-larex-crowdin#6]
Hi!

We're using a organization Crowdin with sub projects but I can't seem to find a possibility to declare a Base_Url for the crowdin API manually in the package?

example:
`https://xxxxxx.crowdin.com/u/projects/69/tools/api`

Is there any possibility to do it with projects in a custom organisation url?

![Uploading image.png…]()

**Comment by Lukasss93** [comment]
Unfortunately I did not have an organisation to test when I created this package, please feel free to contribute by opening a PR.
